name: Update documentation

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string
      PRERELEASE:
        required: true
        type: boolean

jobs:
  trigger-service-update:
    name: Run deployer
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.PRERELEASE == true }}
        name: Send webhook for staging service update
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.STAGING_PORTAINER_DOCUMENTATION_UPDATE_URL }}?tag=${{ inputs.TAG }}
          method: "POST"
          timeout: 40000
      - if: ${{ inputs.PRERELEASE == false }}
        name: Send webhook for production service update
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.PORTAINER_DOCUMENTATION_UPDATE_URL }}?tag=${{ inputs.TAG }}
          method: "POST"
          timeout: 40000
