name: Update documentation

on:
  pull_request:
    types: [closed]
    branches:
      - update-documentation

jobs:
  docker-image:
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    with:
      TAG: ${{ github.sha }}
      PRERELEASE: false

  update-documentation:
    uses: ./.github/workflows/documentation.yml
    secrets: inherit
    needs:
      - docker-image
    with:
      TAG: ${{ github.sha }}
      PRERELEASE: false
