name: Update backend

on:
  pull_request:
    types: [closed]
    branches:
      - update-backend

jobs:
  docker-image:
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    with:
      TAG: ${{ github.sha }}
      PRERELEASE: false

  update-backend:
    uses: ./.github/workflows/backend.yml
    secrets: inherit
    needs:
      - docker-image
    with:
      TAG: ${{ github.sha }}
      PRERELEASE: false
